root = "."
tmp_dir = "tmp"

[build]
  bin = "/tmp/app"
  cmd = "go build -o /tmp/app ./cmd/app/main.go"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "conf"]
  kill_delay = 500 # ms
  log = "app.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "app"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false
