version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - SERVICE_PATH=app
    ports:
      - 9090:9090
    volumes:
      - .:/app